### ISSUE TITLE
Miscellaneous minor issues

### ISSUE THREAD

**Issue by hzovaro** [hzovaro/spaxelsleuth#41]
- [x] In example scripts/notebooks remove references to my own config files (is there a standard way to do this? I guess from command line args..)
- [ ] Is the A_V correction carried out if flux cuts are turned off? 
- [x] Instead of running with and without cuts, perhaps save a copy of the DataFrame before `apply_cuts` is called?
- [x] There's a lot of boilerplate stuff in `make_sami/hector/s7/etc._df()` that could be replaced with a single generic function that is passed the appropriate `_process_gals` call from `sami/hector/s7.py` (see #48)
- [ ] Why are there cells where `D4000 error` < 0?
- [x] Remove all references to column `x, y (pixels)` as it's not really necessary and creates problems with object data types in DataFrames
- [x] Move cosmological parameters to config file
- [x] Updating default config parameters still doesn't seem to work properly in some scenarios
- [x] Figure out why SFRs aren't being calculated
- [x] Fix SFRs - nonzero SFRs in cells classified as 'not classified' but NaNs in those classified as SF
- [x] in `compute_eline_luminosity` and `compute_continuum_luminosity` remove the hard-coded factor of 1e16 - replace this with a `flux_units` arg and create `flux_units` entries for surveys in `config.json`
- [x] Also, pass the `flux_units` variable to the loader functions  
- [x] Rename `Extinction correction applied` to `correct_extinction` 
- [x] Silence warnings during metallicity calculations
- [x] Fix bug where `missing_kinematics_cut` wasn't being added to the DataFrame in `add_columns()`

Columns to rename:

- [x] Rename some emission line ratios to be less confusing, e.g. "log S2 ratio" 
- [x] Rename `x0_px` --> `x0 (pixels)`, etc. in all files 
- [x] ~`Dopita+2016` --> `N2S2Ha`~ `Dopita+2016` refers to a specific polynomial form of the ratio so it doesn't make sense to do this
- [x] Rename `HALPHA lambda_obs (component 1) (Å)` --> `HALPHA lambda_obs (Å) (component 1)`

For renaming:

- [x] Find + replace all offending columns.
- [x] Run `sami_regression_test.py`. Modify it to print out which columns have changed (& double-check that assertion tests still work).
- [x] Overwrite reference DataFrames.
- [x] Once everything is fixed, write a script for loading & renaming columns in the full-sized DataFrames rather than making them again from scratch. 
- [x] Modify keys in local config files as appropriate.
- [x] Double-check that example notebooks still run.

**Comment by n-keerthi-gayathri** [comment]
@hzovaro i would like to try, please assign me this issue

**Comment by hzovaro** [comment]
Sorry @n-keerthi-gayathri, I can't see anything in your profile that suggests you are familiar with integral field unit data sets - I would prefer for someone familiar with handling this sort of data to contribute.
